# Generated by Django 2.2.12 on 2020-12-07 22:14

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions_group', to='otree.Session')),
            ],
            options={
                'db_table': 'instructions_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'instructions_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('passedQuiz', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('q1', otree.db.models.IntegerField(null=True, verbose_name='What is the average dividend payment on one unit of X in period 2?')),
                ('q2', otree.db.models.IntegerField(null=True, verbose_name='If you hold that unit of X till the end of the experiment (9 periods including the current period), what is the average total dividend paid on the unit of X?')),
                ('q3', otree.db.models.IntegerField(null=True, verbose_name='What is the maximum possible dividend paid on the unit of X till the end of the experiment (9 periods including the current period)?')),
                ('q4', otree.db.models.IntegerField(null=True, verbose_name='What is the minimum possible dividend paid on the unit of X till the end of the experiment (9 periods including the current period)?')),
                ('q5', otree.db.models.IntegerField(choices=[[1, '40 francs'], [2, '80 francs'], [3, '20 francs']], null=True, verbose_name='Suppose a buy order of 2 units at 40 francs is submitted.  According to this order, what is the largest amount that would be paid for 1 unit of X?')),
                ('q6', otree.db.models.IntegerField(choices=[[1, 'Purchase 2 units at 40 francs'], [2, 'Purchase 1 unit at 40 francs'], [3, 'Purchase 1 unit at 35 francs'], [4, 'Purchase 1 unit at 30 francs']], null=True, verbose_name='Suppose you placed a buy order of 2 units at 40 francs and another participant placed a sell order of 1 unit at 30 francs.  Which of the following is true?')),
                ('q7', otree.db.models.BooleanField(choices=[[False, 'False'], [True, 'True']], null=True, verbose_name='The dividend paid on each unit of X is the same for every participant.')),
                ('q8', otree.db.models.BooleanField(choices=[[False, 'False'], [True, 'True']], null=True, verbose_name='The value of the asset after the final dividend payment in period 10 is 0.')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instructions.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructions.Subsession')),
            ],
            options={
                'db_table': 'instructions_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructions.Subsession'),
        ),
    ]
