from os import environ
from datetime import datetime

# if you set a property in SESSION_CONFIG_DEFAULTS, it will be inherited by all configs
# in SESSION_CONFIGS, except those that explicitly override it.
# the session config can be accessed from methods in your apps as self.session.config,
# e.g. self.session.config['participation_fee']

_PREQUAL = "3NCAQQYPG7LBIW2OJJ2QJBQNWSHNNF" # This will be generated by the qualification HIT.

_AMK1 = '3Y7Q3XJ70C3IPM4VZCPFTX4B5S675S'
_AMK1_SANDBOX = '39SVKZ8TRSYVRJTOFNWSB59BI4KX86'

SESSION_CONFIG_DEFAULTS = {
    'real_world_currency_per_point': 0.000684,
    'participation_fee': 2.00,
    'doc': "",
    'start_time': '14:00',
    'mturk_hit_settings': {
        'keywords': ['bonus', 'study'],
        'frame_height': 500,
        'minutes_alloted_per_assignment': 90,
        'expiration_hours': 4,
    }
}

SESSION_CONFIGS = [
    #{
    #    'name': 'public_goods',
    #    'display_name': "Public Goods",
    #    'num_demo_participants': 3,
    #    'app_sequence': ['public_goods', 'payment_info'],
    #},
    {
        'name': 'call_market',
        'display_name': "Call Market",
        'num_demo_participants': 4,
        'app_sequence': ['callmkts'],
    },
    {
        'name': 'instructions',
        'display_name': 'Instructions',
        'num_demo_participants': 1,
        'app_sequence': ['instructions'],
    },
    {
        'name': 'qualification',
        'display_name': 'Qualification',
        'num_demo_participants': 1,
        'app_sequence': ['qualification'],
        'participation_fee': 0.01,
        'doc': "",
        'mturk_hit_settings': {
            'keywords': ['bonus', 'study'],
            'title': 'Qual hit for group academic study',
            'description': 'Quick, one question survey',
            'frame_height': 500,
            'template': 'global/mturk_template.html',
            'minutes_allotted_per_assignment': 60*2,
            'expiration_hours': 5,
            'qualification_requirements': [
                {
                    'QualificationTypeId': _AMK1,
                    'Comparator': "DoesNotExist",
                    'ActionsGuarded': "DiscoverPreviewAndAccept",
                },
                {
                    'QualificationTypeId': _PREQUAL,
                    'Comparator': "DoesNotExist",
                    'ActionsGuarded': "DiscoverPreviewAndAccept",
                },
                { #hitapprovalrate
                    'QualificationTypeId': '000000000000000000L0',
                    'Comparator': "GreaterThanOrEqualTo",
                    'IntegerValues':[95]
                },
                { #Number of approved hits
                    'QualificationTypeId': '00000000000000000040',
                    'Comparator': 'GreaterThanOrEqualTo',
                    'IntegerValues': [100]
                },
                { # Only US workers
                    'QualificationTypeId': '00000000000000000071',
                    'Comparator': "EqualTo",
                    'LocaleValues': [{
                        'Country': "US"
                    }]
                }
            ]
        },
        'qualId': 'none',
        'todOrTom': 'Today',
        'month': datetime.now().strftime('%B'),
        'day': datetime.now().day,
    },
    {
        'name': 'call_market_mturk',
        'display_name': "Call Market -- Mturk",
        'num_demo_participants': 3,
        'app_sequence': ['instructions', 'callmkts', 'survey', 'payment_info'],
        'mturk_hit_settings': {
            'title': '!!!OPEN QUICK!!! Group task for academic study.',
            'description': 'A group task for academic study.',
            'template': 'global/MTurkPreview.html',
            'qualification_requirements': [
                {
                    'QualificationTypeId': _PREQUAL, # set this after the qualification HIT finishes
                    'Comparator': "Exists",
                    'ActionsGuarded': "DiscoverPreviewAndAccept"
                },
            ]
        },
    }
]


# ISO-639 code
# for example: de, fr, ja, ko, zh-hans
LANGUAGE_CODE = 'en'

# e.g. EUR, GBP, CNY, JPY
REAL_WORLD_CURRENCY_CODE = 'USD'
USE_POINTS = True
POINTS_CUSTOM_NAME = 'francs'
REAL_WORLD_CURRENCY_DECIMAL_PLACES = 2
POINTS_DECIMAL_PLACES = 2

ROOMS = []

ADMIN_USERNAME = 'admin'
# for security, best to set admin password in an environment variable
ADMIN_PASSWORD = environ.get('OTREE_ADMIN_PASSWORD')

DEMO_PAGE_INTRO_HTML = """ """

SECRET_KEY=''

# if an app is included in SESSION_CONFIGS, you don't need to list it here
INSTALLED_APPS = ['otree']
EXTENSION_APPS = ['callmkts', 'captcha']

ROOT_URLCONF = 'urls'


