# Generated by Django 2.2.12 on 2020-12-07 22:14

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_group', to='otree.Session')),
            ],
            options={
                'db_table': 'survey_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'survey_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('gender', otree.db.models.IntegerField(choices=[[0, 'Female'], [1, 'Male'], [2, 'Other, please specify'], [3, 'Prefer not to answer']], null=True, verbose_name='What is your gender?')),
                ('gender_other', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='If you selected other, please specify')),
                ('age', otree.db.models.IntegerField(null=True, verbose_name='Enter your age')),
                ('citizen', otree.db.models.IntegerField(choices=[[0, 'No'], [1, 'Yes']], null=True, verbose_name='Are you a citizen or permanent resident of the United States?')),
                ('english', otree.db.models.IntegerField(choices=[[0, 'Native'], [1, 'Fluent'], [2, 'Proficient']], null=True, verbose_name='Rate your English')),
                ('race', otree.db.models.IntegerField(choices=[[0, 'American Indian and Alaska Native (having origins in any of the original peoples of North, Central, or South America and maintaining tribal affiliation or community attachment)'], [1, 'Asian (having origins in any of the original people of the Far East, Southeast Asia, or the Indian subcontinent including, for example, Cambodia, China, India, Japan, Korea, Malaysia, Pakistan, the Philippine Islands, Thailand, and Vietnam)'], [2, 'Black or African (having origins in any of the Black racial groups of Africa)'], [3, 'Hispanic (having origins in Mexico, Central or South America)'], [4, 'White (having origins in any of the original peoples of Europe, the Middle East, or North Africa)'], [5, 'Native Hawaiian and other pacific islander (having origins in any of the original peoples of Hawaii, Guam, Samoa, or other Pacific Islands)'], [6, 'Some other race, please specify'], [7, 'Prefer not to answer']], null=True, verbose_name='What race/ethnicity do you identify yourself as?')),
                ('race_other', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='If you selected other, please specify')),
                ('income', otree.db.models.IntegerField(choices=[[0, '$0 to less than $25,000'], [1, '$25,0000 to less than $50,000'], [2, '$50,000 to less than $75,000'], [3, '$75,000 to less than $100,000'], [4, '$100,000 to less than $125,000'], [5, '$125,000 to less than $150,000'], [6, '$150,000 or more'], [7, 'Prefer not to answer']], null=True, verbose_name='What is the total (gross) income last year of your household?')),
                ('education', otree.db.models.IntegerField(choices=[[0, 'Some high school'], [1, 'Completed high school'], [2, 'Some college'], [3, 'Completed college'], [4, 'Some grad/professional school'], [5, 'Completed grad/professional school'], [6, 'Prefer not to answer']], null=True, verbose_name='What is your highest level of education?')),
                ('employment', otree.db.models.IntegerField(choices=[[0, 'Employed, full-time'], [1, 'Employed, part-time'], [2, 'Not employed, looking for work'], [3, 'Not employed, not looking for work'], [4, 'Retired'], [5, 'Student'], [6, 'Prefer not to answer']], null=True, verbose_name='Please indicate your employment status')),
                ('comments', otree.db.models.LongStringField(blank=True, null=True, verbose_name='You may add any comments here')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Subsession')),
            ],
            options={
                'db_table': 'survey_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Subsession'),
        ),
    ]
